LIST P=16F877
INCLUDE P16F877.INC counter1
EQU 0X20 couter2
EQU 0X21 ORG 0
BSF STATUS,5
CLRF TRISB
MOVLW H'07'
MOVWF ADCON1
MOVLW b'11111111'
MOVWF TRISA
BCF STATUS,5
movlw b'00000000'
movwf PORTB
movlw b'11111111'
movwf TRISC .port c and d set as input
movwf TRISD
LABEL1
    BSF PORTB,0
    RB0 logic1
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    BCF PORTB,0
    RB0 logic0
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    BSF PORTB,1
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    BCF PORTB,1
    CALL DELAY
    GOTO LABEL1
    DELAY
    movfw PORTC
    movwf counter1
TEST2
    mOVWF couter2
TEST1
    DECFSZ couter2,F
    GOTO TEST1
    DECFSZ counter1,F
    GOTO TEST2
    RETURNEND